@startuml
'skin BlueModern
skinparam backgroundColor #F4F4F4
hide footbox
'''''


participant ClientReceptionist as recep <<Actor>>
participant ClientSupervisor as super <<Actor>>

participant "Client" as client <<Client>>

-> recep: allocate
activate recep
recep -> super: context actorOf
activate super
recep -> super: context watch

super -> client: context actorOf
activate client
super -> client: context watch

client -> client: initialize
client -> super: m@Register(ClientType)
super -> recep: forward m

recep -> super: m@Registered(ClientType)
super -> client: forward m

recep -> super: m@SetSubscribers(subscribers)
super -> client: forward m

client -> client: Subscribers = \nsubscribers

deactivate recep
deactivate client
deactivate super


@enduml