@startuml
'skin BlueModern
skinparam backgroundColor #F4F4F4
hide footbox

actor "API User" as U

box "API"
participant "Subject" as O <<Observable>>
participant "API" as A <<Library>>
end box

box "Core-Runtime"
    participant ClientHandler as CH <<Actor>>
    participant Receptionist as R <<Actor>>
    participant "MAVLink Converter" as MLC <<Library>>
    participant HeliosUART as HU <<Actor>>
end box

participant UART <<Hardware>>

activate U
U -> A: Subscribe(MessageType)
activate A
A -> O: allocate
O --> A: ref: Subject
A -> A: store(ref, id)

A --> U: subject: Subject
A -> CH: Subscribe(MessageType, id)
activate CH
CH -> R: Subscribe(MessageType, id)
activate R

loop Read Loop
activate UART
UART <-]: Pkg: Byte[]
UART -> HU:  Pkg
activate HU
HU -> MLC: convert(Pkg)
activate MLC
HU <-- MLC: convertedPkg: MAVLinkMsg
deactivate MLC
HU -> R: msg: MAVLinkMsg
deactivate HU
R -> R: sendToSubscribers(msg)
opt if subscribed
R -> CH: (msg, id): MAVLinkMsg
deactivate R
CH -> A: (msg, id): MAVLinkMsg
deactivate CH
A -> O: onNext(msg)
deactivate A
O -> U: msg

end opt
end loop

@enduml